version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3-browsers
      #=ChromeHeadlessNoSandbox

    working_directory: ~repos      

    steps:
      - checkout

      - restore cache:
          keys:
          - v1-dependencies-{{ checksum package.json }}
          - v1-dependencies-
          - run: yarn install
      - save cache:
          paths:
            - node_modules
          keys:
          - v1-dependencies-{{ checksum package.json }}   
          
      - run: yarn ng build --prod
      - run: yarn ng test --single-run 
