version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3-browsers
      

    working_directory: mts      
      chown -R $USER:$USER mts

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum package.json }}
          - v1-dependencies-
      - run: yarn install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum package.json }}   
          
      - run: yarn ng build --prod
      - run: yarn ng test --single-run 
